# 🔢 Introduction to NumPy

**NumPy**, short for **Numerical Python**, is an essential, highly optimized open-source library used for high-performance scientific computing and data analysis.

📌 **Core Capabilities of NumPy:**
* **Python Library Ecosystem**: It provides the foundational array data structures that power modern data science packages like Pandas, SciPy, and Scikit-learn.
* **Advanced Mathematical Tools**: It contains pre-built, fast functions designed for linear algebra equations, Fourier Transform operations, and complex multi-dimensional matrix operations.


### 🧪 1. Importing NumPy and Creating an Array

To use NumPy, you first bring the library into your current script layout using the `import numpy` command statement. The core object structure in NumPy is the **ndarray** (N-dimensional array), which can be initialized by wrapping a standard Python list inside the `numpy.array()` constructor method.

📌 **Key Array Behaviors to Notice:**
* **Space-Separated Values**: When you print a NumPy array, the output elements are separated by blank spaces `[1 2 3 4 5]` instead of the classic comma-separated syntax `[1, 2, 3, 4, 5]` used by standard lists.
* **Homogeneous Elements**: Unlike Python lists, every element inside a NumPy array must be of the exact same data type (e.g., all integers or all floats) for optimal memory performance.


In [3]:
# Import the complete numpy library space
import numpy

# Convert a standard python list sequence into a highly optimized NumPy array
new_arr = numpy.array([1, 2, 3, 4, 5])

# Print out the computed result matrix payload
print(new_arr)

[1 2 3 4 5]


### 🏷️ 2. Importing NumPy with a Standard Alias (`as np`)

In the data science community, it is a universal convention to import NumPy using the `as` keyword to create a shorter nickname or alias: `np`. This helps keep your code clean, concise, and easy to read by saving you from typing out the full word `numpy` every time you call an array constructor or mathematical method.


In [4]:
# Import the library using the industry-standard short nickname
import numpy as np

# Create the array structure using the short prefix format
new_arr = np.array([1, 2, 3, 4, 5])

# Print out the results payload
print(new_arr)

[1 2 3 4 5]


### 🔍 3. Checking NumPy Version and Array Object Type

You can inspect the metadata of your environment and object types using built-in string attributes and functions.

📌 **Inspecting Metadata:**
* **`np.__version__`**: A special built-in string attribute that returns the exact version number of the installed NumPy library.
* **`type()`**: Passing a NumPy array into the native Python `type()` function reveals its underlying class structure, which is classified as an **`ndarray`** (N-dimensional array).


In [5]:
# Print out the current library version installed in your workspace
print(np.__version__)

2.3.5


In [6]:
# Verify the object class structure of array 
print(type(new_arr))

<class 'numpy.ndarray'>


### 📦 4. Creating a NumPy Array from a Tuple

The `np.array()` constructor is flexible and accepts any array-like collection object. In addition to standard Python lists, you can pass a standard Python **tuple** wrapped in parentheses `(1, 2, 3, 4)` to initialize a valid, highly-optimized NumPy `ndarray`.


In [7]:
# Initialize a NumPy array passing a tuple instead of a list
another_arr = np.array((1, 2, 3, 4))

# Print the resulting space-separated array output
print(another_arr)

[1 2 3 4]


### 🎯 5. Creating a 0-D Array (Scalar)

A **0-D (Zero-Dimensional) array** represents a single scalar value. It has no dimensions, axes, or indexing columns. You create a 0-D array by passing a raw standalone numeric value directly into the `np.array()` constructor.

In [9]:
# Create a 0-D scalar array 
arr = np.array(30)

# Print out the value
print(arr)

30


### 6. Creating a 1-D Array (Vector)

A 1-D (One-Dimensional) array contains 0-D elements arranged in a single linear sequence. It functions as a standard mathematical vector. It is created by passing a single list structure into the array constructor.

In [10]:
# 1-D Array
new_arr = numpy.array([1, 2, 3, 4, 5])
print(new_arr)

[1 2 3 4 5]


### 7. Creating a 2-D Array (Matrix)

A 2-D (Two-Dimensional) array contains 1-D arrays as its elements. It represents a mathematical matrix with rows and columns. It is created by passing a nested list structure containing multiple sub-lists into the array constructor.


In [11]:
# 2-D Array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


### 8. Creating a 3-D Array (Tensor)

A 3-D (Three-Dimensional) array contains 2-D arrays as its elements. It represents an array of matrices. It is created by passing a nested structure containing multiple levels of sub-lists into the array constructor.

In [12]:
# 3-D Array
arr2 = np.array([[[1, 3, 4], [6, 7, 8]], [[1, 2, 3], [6, 7, 8]]])
print(arr2)

[[[1 3 4]
  [6 7 8]]

 [[1 2 3]
  [6 7 8]]]


### 📏 9. Checking Array Dimensions Using `.ndim`

The `.ndim` attribute returns an integer representing the total number of dimensions (axes) present inside a NumPy array object instance.

In [13]:
# Check number of dimensions
a = np.array(30)
b = numpy.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 3, 4], [6, 7, 8]], [[1, 2, 3], [6, 7, 8]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### 🚀 10. Creating Higher-Dimensional Arrays with `ndmin`

The `ndmin` parameter in the `np.array()` constructor forces the array to have a minimum number of dimensions. NumPy embeds the inner data sequence inside nested square brackets until it reaches the requested dimensional depth.


In [14]:
# Higher dim arr
new_arr = np.array([1, 2, 3, 4], ndmin=5)

print(new_arr)
print("The number of dimensions:", new_arr.ndim)

[[[[[1 2 3 4]]]]]
The number of dimensions: 5


### 🎯 11. Accessing 1-D Array Elements via Indexing

Array indexing allows you to access individual elements in a 1-D NumPy array. NumPy arrays use a zero-based indexing system, meaning the first element is at index `0`, the second is at index `1`, and so on.


In [15]:
# Initialize a 1-D array
arr1 = np.array([10, 20, 30, 40])

# Access and print elements using zero-based indices
print(arr1[0])
print(arr1[1])
print(arr1[2])

10
20
30


### 🗂️ 12. Accessing 2-D Array Elements via Indexing

To access elements from a 2-D array, use comma-separated integers representing the dimension indices. The first index selects the row (or sub-array), and the second index selects the column (the specific element inside that row).


In [17]:
# Access 2-D Arr
newArr = np.array([[10, 20, 30], [40, 50, 60]])

print("The second element in 1st dim is:", newArr[0, 1])

The second element in 1st dim is: 20


In [18]:
print("The third element in 2nd dim is:", newArr[1, 2])

The third element in 2nd dim is: 60


### 📦 13. Accessing 3-D Array Elements via Indexing

To access elements from a 3-D array, use three comma-separated integers. The first index selects the 2-D matrix, the second index selects the row within that matrix, and the third index selects the specific column element.

In [19]:
# Initialize 3-D Array
arr3 = np.array([[[1, 3, 4], [6, 7, 8]], [[1, 2, 3], [6, 7, 8]]])

# The third element in the second array of the first array
print(arr3[0, 1, 2])

8


### 🔪 14. Slicing Arrays using Index BoundarieS

Slicing in NumPy means pulling out elements from one given index to another given index. You pass slice ranges instead of individual index values using a colon separator syntax: `[start:end]`. The slice includes the element at the start index but excludes the element at the end index.


In [20]:
import numpy as np

new_arr = np.array([1, 2, 3, 4, 5, 6])
print(new_arr[1:4])

[2 3 4]


### 🛑 15. Slicing with Omitted End Indices

If you leave out the end index value in the slicing syntax `[start:]`, NumPy defaults to reading every element from the specified start point all the way to the very end of the array sequence.


In [21]:
print(new_arr[3:])

[4 5 6]


### 🏁 16. Slicing with Omitted Start Indices

If you leave out the start index value in the slicing syntax `[:end]`, NumPy assumes a default start value of index 0 and reads elements up to, but excluding, the specified end position.

In [22]:
print(new_arr[:3])

[1 2 3]


### ⬅️ 17. Slicing with Negative Index Boundaries

You can use negative index numbers to slice arrays starting from the tail end instead of the front. The index value `-1` represents the last item, `-2` represents the second to last item, and so on.

In [23]:
print(new_arr[-4:-1])

[3 4 5]


### 👣 18. Slicing Arrays with Step Values

You can use a third value inside the slice syntax to define the step stride: `[start:end:step]`. The step determines the increment value used when moving from the start index to the end index. For example, a step of `2` tells NumPy to skip every other element within the chosen boundaries.

In [24]:
# Slice from index 1 to index 4 with a step value of 2
print(new_arr[1:4:2])

[2 4]


### 🗂️ 19. Slicing 2-D Arrays

To slice elements from a 2-D array, combine row indexing with column slicing using a comma separator. The first argument selects the targeted row, and the second argument provides the index slice range (`[start:end]`) to pull elements out of that specific row.

In [26]:
# Slice 2-d
new_arr = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])
print(new_arr[1, 1:4])

[20 30 40]


### 👥 20. Slicing Specific Columns Across Multiple Rows

You can slice elements from multiple rows simultaneously by passing a row index slice range (`[start:end]`) before the comma, followed by a single integer to target a specific column. This allows you to extract vertical columns of data across rows.

In [27]:
# Slice column index 2 from row index 0 up to (but excluding) row index 2
print(new_arr[0:2, 2])

[ 3 30]


### 👥 21. Slicing Ranges of Columns Across Multiple Rows

You can slice a multi-dimensional sub-matrix from a 2-D array by combining a row index range with a column index range. This operation extracts a specific window of columns across the selected row indices simultaneously.

In [28]:
# Slice column indices 1 to 4 across row indices 0 up to 2
print(new_arr[0:2, 1:4])

[[ 2  3  4]
 [20 30 40]]


# 🔤 Data Types in NumPy (`dtype`)

NumPy arrays have a fixed data type for all elements to ensure optimized memory allocation and fast computation. You can inspect an array's data type using the `.dtype` property. 

📌 **NumPy Data Type Single-Character Codes:**
* **`i`**: Integer
* **`b`**: Boolean
* **`u`**: Unsigned integer
* **`f`**: Float
* **`c`**: Complex float
* **`m`**: Timedelta
* **`M`**: Datetime
* **`O`**: Object
* **`S`**: String
* **`U`**: Unicode string
* **`V`**: Fixed chunk of memory for another type (void)

### 🔍 1. Checking Array Data Types with `.dtype`

The `.dtype` attribute allows you to inspect the data type of the elements stored inside an array object. NumPy automatically determines an appropriate data type based on the values provided during array initialization.


In [29]:
import numpy as np

new_arr = np.array([1, 2, 3])
new_arr2 = np.array(["banana", "fig", "watermelon"])

print(new_arr.dtype)
print(new_arr2.dtype)

int64
<U10


### 🏷️ 2. Defining Array Data Types During Initialization

You can force a specific data type when creating an array by passing the `dtype` parameter into the `np.array()` constructor. For instance, passing `dtype="S"` forces NumPy to store string items as fixed-length byte-strings instead of standard Unicode strings.


In [30]:
import numpy as np

new_arr = np.array([1, 2, 3])
new_arr2 = np.array(["banana", "fig", "watermelon"], dtype="S")

print(new_arr.dtype)
print(new_arr2.dtype)

int64
|S10


# Mathematical operations using NumPy

### ➕ 1. NumPy Scalar Arithmetic Operations

NumPy allows you to perform element-wise arithmetic operations directly on array objects using standard mathematical operators (like `+`, `-`, `*`, `/`). When you apply an arithmetic operation between an array and a single scalar value, NumPy automatically applies that operation to every individual element inside the array.

In [31]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a + 2
print(b)

[3 4 5 6]


### 🤝 2. Element-Wise Vector Arithmetic Operations

When you perform arithmetic operations between two NumPy arrays of the exact same shape, the mathematical operator acts element-wise. This means each element in the first array is matched and combined directly with the element at the corresponding index position in the second array.

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a + b
print(c)

[11 22 33 44]


### ✖️ 3. NumPy Scalar Multiplication

Multiplying a NumPy array by a scalar value scales every individual element inside that array by the specified multiplier. The operation computes the element-wise product instantly across the entire array structure.

In [33]:
a = np.array([1, 2, 3, 4])
b = 4 * a
print(b)

[ 4  8 12 16]


### ⚫ 4. Computing Vector Dot Product using `np.dot()`

The dot product of two vectors is calculated by multiplying corresponding elements together and then summing up all those individual products. For 1-D arrays, the function `np.dot(a, b)` returns a single scalar value tracking this total sum.

$$\text{Dot Product} = (1 \times 10) + (2 \times 20) + (3 \times 30) + (4 \times 40) = 10 + 40 + 90 + 160 = 300$$

In [34]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
np.dot(a, b)

np.int64(300)

### 📈 5. Element-Wise Exponential Using `np.exp()`

The `np.exp()` function calculates the exponential of all elements in the input array. It computes $e^x$ for each individual value $x$, where $e$ is Euler's number (approximately 2.71828).

In [36]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(np.exp(a))


[ 2.71828183  7.3890561  20.08553692 54.59815003]
